# This is a basic workflow to help you get started with Actions

name: "PR CI"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [master, dev]

env:
  configuration: Release
  solution: Moedim.Mapper.sln

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to fetch all history for all tags and branches

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore ${{ env.solution }} -v quiet

      - name: Build
        run: dotnet build ${{ env.solution }} --configuration ${{ env.configuration }}

      - name: Test
        run: dotnet test --no-build --verbosity normal